project_id = "iyqsbjawaampgcavsgcz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.ai-chat]
verify_jwt = true

[functions.create-project-from-quote]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.create-custom-payment]
verify_jwt = true

[functions.submit-custom-request]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-deliverable-notifications]
verify_jwt = false

[functions.send-quote-notifications]
verify_jwt = false

[functions.create-google-meet]
verify_jwt = true

[functions.create-jitsi-meet]
verify_jwt = true

[functions.compute-matching]
verify_jwt = false

[functions.match-experts]
verify_jwt = false

[functions.compute-matches]
verify_jwt = false

[functions.send-invitations]
verify_jwt = false

[functions.auto-match-pending-briefs]
verify_jwt = false

[functions.create-brief-from-catalog]
verify_jwt = false

[functions.auto-ai-matching]
verify_jwt = false

[functions.respond-to-invite]
verify_jwt = true

[functions.select-expert-for-brief]
verify_jwt = true

[functions.create-project-from-acceptance]
verify_jwt = false

[functions.submit-cr]
verify_jwt = false

[functions.get-match-results]
verify_jwt = true

[functions.send-rfp]
verify_jwt = true

[functions.get-outcome-cards]
verify_jwt = false

[functions.guest-save-continue]
verify_jwt = false

[functions.list-tools]
verify_jwt = false

[functions.save-freelancer-profile]
verify_jwt = true

[functions.suggest-tool]
verify_jwt = true

[functions.add-case-study]
verify_jwt = true

[functions.expert-selection-notifications]
verify_jwt = false

[functions.schedule-intro-call]
verify_jwt = true

[functions.create-project-from-proposal]
verify_jwt = false

[functions.create-assurance-subscription]
verify_jwt = true

[functions.auto-nudge-proposals]
verify_jwt = false

[functions.auto-nudge-client-to-choose]
verify_jwt = false

[functions.auto-nudge-pay-m1]
verify_jwt = false

[functions.auto-qa-retry]
verify_jwt = false

[functions.retainer-offer-post-completion]
verify_jwt = false

[functions.stale-project-poke]
verify_jwt = false

[functions.enhanced-stripe-webhook]
verify_jwt = false

[functions.submit-brief]
verify_jwt = false

[functions.brief-sensemaking]
verify_jwt = false

[functions.process-email-outbox]
verify_jwt = false

[functions.send-scorecard-report]
verify_jwt = false

[functions.process-scorecard-emails]
verify_jwt = false

[functions.trigger-scorecard-alerts]
verify_jwt = false

[functions.scorecard-webhook]
verify_jwt = false

[edge_runtime]
enabled = true
